### ISSUE TITLE
👋 Introduction 

### ISSUE THREAD

**Issue by okjake** [GSG-G8/events-booker#125]
Hi all! 

I'm Jake, I'll be helping out with some code reviews. You can get me on discord (Jake~) if you have any questions or would like to set up some time to chat more generally 🙂

Great progress on the app! I'd like to run it locally to understand it better, could you help me with one thing?

I see you have a config.env for handling the secret keys which isn't committed into the repository which is perfect, but it can be useful to have in the repository a file called something like config.env.template. 

This can be used by people who are running the code for the first time to know which keys they need to add to run the app, it can look like config.env but without any sensitive values, eg:

```
PORT
POSTGRES_URL
...
```

**Comment by AhmedSafi97** [comment]
Hi Jake,
It's nice to have you here, I'm looking forward for your reviews and to share some of your experience :smile:

**Comment by AlaaTaima** [comment]
Hi Jake, 
nice to meet you here, we will be lucky to share your experience.

**Comment by mariamisa** [comment]
Hello Jake, I'm looking forward for your reviews and to share some of your experience.

**Comment by MohammedIrheem** [comment]
Hi there, 
I hope that you are well. I'd love that you are joining us in this project, and we are looking forward to getting some of your experiences.
Cheers

**Comment by Rawan96** [comment]
Hi jake,
Nice to meet you, we are looking forward to your helpful feedback.
