### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by okjake** [GSG-G8/events-booker#143]
Hi all!

I've added a detailed code review here https://github.com/okjake/events-booker/pull/1

There are a few suggestions for enhancements and things to research for next time, If you have any questions or comments at any point you can leave them here or get me on discord or jakepyne@gmail.com

Keep up the good work!

**Comment by Rawan96** [comment]
Hi Jake,

Thank you for taking the time to review our code. We will take it into consideration when we will refactor the code. 

Sincerely,
Rawan
