### ISSUE TITLE
app.all instead of app.use for the protection middleware 

### ISSUE THREAD

**Issue by AhmedSafi97** [GSG-G8/events-booker#88]
relating to **issue** #74, 
to solve the problem explained in the mentioned issue, we put all protected routes in an array and handdled these routes with the protection middlware using router.use(), **BUT** we still have the same issue, I've tried to make a **GET** request to **/api/v1/users/whatever** I expected a response **Page not found** with status **404** instead I got a response **un-auth** with status **401** this mean the request passed the protection middleware even though it's supposed to be unhandled route not a protected route 
**To solve this issue** I suggest we use router.all() instead of router.use() to handle only the protected routes with the protection middleware ,  [read more about the difference between the two](https://bambielli.com/til/2016-12-27-app-use-app-all/)

**Comment by AhmedSafi97** [comment]
@Rawan96 @mariamisa @MohammedIrheem @AlaaTaima 
**let me guys hear what you think**

**Comment by AlaaTaima** [comment]
good note @AhmedSafi97 :+1: 
here, with our case we need to use router.all.
it is added and merged to the master.
[look here for more explaination](https://bambielli.com/til/2016-12-27-app-use-app-all/)
@Rawan96 @MohammedIrheem @mariamisa  see it .
